version: "3"

services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
#      MYSQL_RANDOM_ROOT_PASSWORD: YES
#      MYSQL_ONETIME_PASSWORD: YES
      MYSQL_USER: sa
      MYSQL_PASSWORD: sapass
      MYSQL_DATABASE: management_system
    volumes:
      - datavolume:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  datavolume:
